<?php

/**
 * @file
 * Contains hook implementations for the Loyalist Core module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_FORM_ID_alter.
 */
function loyalist_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change Views|Exposed Filter criteria|Fulltext search|Filter identifier=fulltext to 'search' type (UI: 'x').
  if (isset($form['fulltext'])) {
    $form['fulltext']['#type'] = 'search';
  } elseif (isset($form['category'])){
    // Also change input type for Top Subjects combined fields filter.
    $form['category']['#type'] = 'search';
  }

  switch ($form['#id']) {
    case 'views-exposed-form-search-display-page-search':
      $form['#attached']['library'][] = 'loyalist_core/search_input_required';
      break;
  }
}

/**
 * Implements hook_views_pre_render.
 */
function loyalist_core_views_pre_render(ViewExecutable $view) {
  if (strpos($view->getTitle(), 'Owl Carousel') !== false) {
    // Attach OwlCarousel2 library for Views displays w/ 'Owl Carousel' contained within the title.
    $view->element['#attached']['library'][] = 'the_loyalist_collection/owlcarousel2';
  }

}
