<?php

/**
 * @file
 * Contains hook implementations for the Loyalist Core module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_FORM_ID_alter.
 */
function loyalist_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change Views|Exposed Filter criteria|Fulltext search|Filter identifier=query to 'search' type (UI: 'x').
  if (isset($form['query'])) {
    $form['query']['#type'] = 'search';
  } elseif (isset($form['category'])){
    // Also change input type for Top Subjects combined fields filter.
    $form['category']['#type'] = 'search';
  }

  switch ($form['#id']) {
    case 'views-exposed-form-search-display-page-search':
      $form['#attached']['library'][] = 'loyalist_core/search_input_required';
      break;
  }
}

/**
 * Implements hook_page_attachments().
 */
function loyalist_core_page_attachments(array &$attachments) {
  // Conditionally add library attachment for Claro theme (administration theme overrides).
   if (\Drupal::service('theme.manager')->getActiveTheme()->getName() === "claro") {
    $attachments['#attached']['library'][] = 'the_loyalist_collection/claro-ck5admin-overrides';
  }
}
